// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Steamfinity.Cloud;

#nullable disable

namespace Steamfinity.Cloud.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230417211920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AccountName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset>("AdditionTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Alias")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("CooldownExpirationTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset?>("CreationTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<decimal?>("CurrentGameId")
                        .HasColumnType("NUMBER(20)");

                    b.Property<string>("CurrentGameName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("HasPrimeStatus")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool?>("IsCommentingAllowed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool?>("IsCommunityBanned")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool?>("IsProfileSetUp")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool?>("IsProfileVisible")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LastEditTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset?>("LastSignOutTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset?>("LastUpdateTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("LaunchParameters")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Notes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("NumberOfDaysSinceLastBan")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("NumberOfGameBans")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("NumberOfVACBans")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("OptimizedAccountName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OptimizedAlias")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OptimizedCurrentGameName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OptimizedLaunchParameters")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OptimizedNotes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OptimizedProfileName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OptimizedProfileUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OptimizedRealName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ProfileName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RealName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("SkillGroup")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("SteamId")
                        .HasColumnType("NUMBER(20)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("SteamId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.AccountInteraction", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("AccountId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountInteractions");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("InstigatorId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("NewValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("TargetAccountId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("TargetLibraryId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("InstigatorId");

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("TargetLibraryId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LastSignInTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset>("SignUpTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Hashtag", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("AccountId", "Name");

                    b.HasIndex("Name");

                    b.ToTable("Hashtags");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Membership", b =>
                {
                    b.Property<Guid>("LibraryId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Role")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("LibraryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Account", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.Library", "Library")
                        .WithMany("Accounts")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.AccountInteraction", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.Account", "Account")
                        .WithMany("Interactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationUser", "User")
                        .WithMany("AccountInteractions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Activity", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationUser", "Instigator")
                        .WithMany("InstigatedActivities")
                        .HasForeignKey("InstigatorId");

                    b.HasOne("Steamfinity.Cloud.Entities.Account", "TargetAccount")
                        .WithMany("Activities")
                        .HasForeignKey("TargetAccountId");

                    b.HasOne("Steamfinity.Cloud.Entities.Library", "TargetLibrary")
                        .WithMany("Activities")
                        .HasForeignKey("TargetLibraryId");

                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationUser", "TargetUser")
                        .WithMany("AffectingActivities")
                        .HasForeignKey("TargetUserId");

                    b.Navigation("Instigator");

                    b.Navigation("TargetAccount");

                    b.Navigation("TargetLibrary");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Hashtag", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.Account", "Account")
                        .WithMany("Hashtags")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Membership", b =>
                {
                    b.HasOne("Steamfinity.Cloud.Entities.Library", "Library")
                        .WithMany("Memberships")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steamfinity.Cloud.Entities.ApplicationUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Account", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Hashtags");

                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AccountInteractions");

                    b.Navigation("AffectingActivities");

                    b.Navigation("InstigatedActivities");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Steamfinity.Cloud.Entities.Library", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Activities");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
